### ISSUE TITLE
How are the presenter and view connected initially?

### ISSUE THREAD

**Issue by gismofx** [mrts/winforms-mvp#1]
Maybe I'm missing it, but I see that the presenter is created , but never passed into the view? How are the presenter and view connected initially?

In Program.cs, do you need to set the presenter property before running the form?

**Comment by mrts** [comment]
Presenter sets a [backreference to itself in the view during construction](https://github.com/mrts/winforms-mvp/blob/master/WinFormsMVP/WinFormsMVP/Presenter/CustomerPresenter.cs#L15):

        public CustomerPresenter(ICustomerView view, ICustomerRepository repository)
        {
            _view = view;
            view.Presenter = this; // ← here's the trick
            _repository = repository;

            UpdateCustomerListView();
        }

This can be done the other way around as well if the view is activated before the presenter, see [this StackOverflow answer](https://stackoverflow.com/questions/32184406/how-to-implement-mvp-using-vaadin-cdi-and-navigator/36657253#36657253).

**Comment by gismofx** [comment]
Thank you for clarifying. Your example really helped me understand the concept.

**Comment by mrts** [comment]
Happy to hear that 😊!
